version: '3'

services:

  playgreen-api:
    container_name: playgreen-api
    image: playgreen-image
    ports:
      - 3001:3001
    environment:
      - HOST_DATABASE=${HOST_DATABASE}
      - PORT_DATABASE=${PORT_DATABASE}
      - USER_DATABASE=${USER_DATABASE}
      - PASS_DATABASE=${PASS_DATABASE}
      - NAME_DATABASE=${NAME_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - playgreen-database





  playgreen-database:
    container_name: playgreen-database
    image: mysql:latest
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "${PORT_DATABASE}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS_DATABASE}
      MYSQL_DATABASE: ${NAME_DATABASE}
      MYSQL_USER: ${USER_DATABASE}
      MYSQL_PASSWORD: ${PASS_DATABASE}

volumes:
  database_data:
